version: 2.0
jobs:
  build:
    docker:
      - image: membrane/bionic-membrane:latest
    environment:
      MIX_ENV: test
      PKG_CONFIG_PATH: '/root/app/ext/'
    working_directory: '~/app'

    steps:
      - checkout
      - run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
      - run: apt-get install -qq libmp3lame-dev
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
